### ISSUE TITLE
I am a noob , i don't how to edit the onedrive of you don't mine edit and send sir plzzzz!!🙏🙏🙏

### ISSUE THREAD

**Issue by Nishok000123** [hlf20010508/telegram-onedrive#2]
Please sir I am student i want to store all my videos from tele to one drive kindly edit the onedrive.py with developer authentication sirrr !!🙏🙏

**Comment by hlf20010508** [comment]
I’m also a student, and I’m about to graduate. So I’m very busy this year.
You have to wait until next year, soon in Janurary, or later maybe in April.

**Comment by Nishok000123** [comment]
Okay

**Comment by hlf20010508** [comment]
Try this:
When creating Azure Application, `Supported account types` choose `Accounts in any organizational directory (Any Microsoft Entra ID tenant - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)`.
If this still doesn't work, I don't know what to do. Cause my dev account seems to be banned by Microsoft, that my Authorization code is always expired.

**Comment by hlf20010508** [comment]
And I've googled this expire problem, shows that it's because too many people use dev account to get the best deal. So Microsoft chooses to ban this.
I've been working on this for hours, and end with failure.
