### ISSUE TITLE
Some Question

### ISSUE THREAD

**Issue by hirockstar** [hlf20010508/telegram-onedrive#5]
with this can we upload large file via URL like this [Link](https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-72841/ACCBB990-9842-4C7D-AD93-AE8E62D76179/iPhone16,2_17.0.3_21A360_Restore.ipsw) .
our account it business account dose it support that?

**Comment by hlf20010508** [comment]
Hey there, business account has been supported, as long as you're not using **educational account without admin**.

**Comment by therockstarind** [comment]
thanks

**Comment by therockstarind** [comment]
bro is there way to talk to you..?

**Comment by hlf20010508** [comment]
> bro is there way to talk to you..?
> 
> 

https://t.me/hlf01
