### ISSUE TITLE
This is the problem I'm having

### ISSUE THREAD

**Issue by reyfull** [hlf20010508/telegram-onedrive#9]
docker-compose.yml
![image](https://github.com/hlf20010508/telegram-onedrive/assets/111069621/bf735c97-64ac-46ba-9ff7-f1d639a77855)

telegram
![telegram](https://github.com/hlf20010508/telegram-onedrive/assets/111069621/3265a159-cdd8-4d8a-94ff-0ad70e9bbd6d)

**Comment by hlf20010508** [comment]
Oh there's a bug in version 3.7.
Please use 3.6 first. I'm solving it.

**Comment by hlf20010508** [comment]
Fixed. You can try the latest again.

**Comment by reyfull** [comment]
It works fine after switching to version v3.6, but I can't receive the code.
![code](https://github.com/hlf20010508/telegram-onedrive/assets/111069621/56a4b794-df1b-421e-8276-bafd020c20b1)

**Comment by hlf20010508** [comment]
<img width="300" alt="image" src="https://github.com/hlf20010508/telegram-onedrive/assets/76218469/8e60009b-5ff6-48a9-ba48-00cac1b79ead">

You don't receive code like this?

**Comment by reyfull** [comment]
I only received it once, and then I can no longer receive the code.
I checked the log and the following display appeared:
![log](https://github.com/hlf20010508/telegram-onedrive/assets/111069621/a34bdf6a-b964-45f4-b892-ea3f577dfd87)

telethon.errors.rpcerrorlist.SendCodeUnavailableError: Returned when all available options for this type of number were already used (e.g. flash-call, then SMS, then this error might be returned to trigger a second resend) (caused by ResendCodeRequest)

**Comment by hlf20010508** [comment]
Ok, update to latest version, or recreate your container.
I recommend you update to latest version.
